Repository geekelo/fenaj-schedula_API, pull requests merged in 2023-12, with the labels that each got.

#29 Set up Spa-sessions and Reservations tables
  Gemfile
  Gemfile.lock
  app/assets/images/img.jpg
  app/models/item.rb
  app/models/reservation.rb
  app/models/user.rb
  config/database.yml
  db/migrate/20231201053133_create_active_storage_tables.active_storage.rb
  db/migrate/20231201104511_create_items.rb
  db/migrate/20231201104650_create_reservations.rb
  db/schema.rb
  db/seeds.rb
Labels: Fatima Task, Backend

#30 Set up controllers for spa sessions and reservations
  app/controllers/api/items_controller.rb
  app/controllers/api/reservations_controller.rb
  app/controllers/api/users_controller.rb
  app/helpers/api/items_helper.rb
  app/helpers/api/reservations_helper.rb
  app/helpers/api/users_helper.rb
Labels: Fatima Task, Backend

#31 Add index and show methods to controllers
  .ruby-version
  Gemfile.lock
  app/controllers/api/items_controller.rb
  app/controllers/api/reservations_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/sessions_controller.rb
  config/routes.rb
Labels: Joyce Task, Backend

#32 Set up controller method to add spa sessions
  .gitignore
  Rakefile
  app/controllers/api/items_controller.rb
  bin/rails
  bin/rake
  bin/setup
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/permissions_policy.rb
  config/initializers/session_store.rb
  config/puma.rb
  config/routes.rb
  db/migrate/20231130152605_create_users.rb
  db/migrate/20231201053133_create_active_storage_tables.active_storage.rb
  db/schema.rb
  db/seeds.rb
Labels: Nasir Task, Backend

#34 Update:Add Delete function to Reservation
  app/controllers/api/reservations_controller.rb
Labels: Yemi Task, Backend

#36 Implement user authentication
  .dockerignore
  .gitattributes
  .gitignore
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  app/assets/style.css
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/api/v1/authentication_controller.rb
  app/controllers/api/v1/item_controller.rb
  app/controllers/api/v1/registration_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/.keep
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/concerns/.keep
  app/models/json_web_token.rb
  app/models/user.rb
  app/serializers/user_serializer.rb
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  bin/bundle
  bin/docker-entrypoint
  bin/rails
  bin/rake
  bin/setup
  config.ru
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/credentials.yml.enc
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  config/storage.yml
  db/migrate/20231208144021_create_users.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/.keep
  log/.keep
  public/robots.txt
  storage/.keep
  tmp/.keep
  tmp/pids/.keep
  tmp/storage/.keep
  vendor/.keep
Labels: Eloghene Task, Backend

#37 Models
  .DS_Store
  .ruby-version
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/images/.keep
  app/assets/images/img.jpg
  app/assets/stylesheets/application.css
  app/controllers/api/v1/registration_controller.rb
  app/controllers/api/v1/reservation_controller.rb
  app/models/item.rb
  app/models/reservation.rb
  app/models/user.rb
  bin/rails
  bin/rake
  bin/setup
  config/application.rb
  config/boot.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/puma.rb
  db/migrate/20231208153557_create_items.rb
  db/migrate/20231208153740_create_reservations.rb
  db/schema.rb
Labels: Joyce Task, Backend
